# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np

arr = np.arange(0,10)
arr = arr.reshape(2, len(arr) // 2)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.repeat(np.array((1)), 10).reshape(2,5)

np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [6]:
arr3 = np.arange(0,10).reshape(2,5)
arr4 = np.repeat(np.array(1), 10).reshape(2,5)

np.hstack((arr3, arr4))


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [7]:
array = np.asarray([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [9]:

y = np.arange(0,15).reshape(3,5)
y.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [10]:
array = np.asarray([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5, 3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [11]:

arr = np.arange(25).reshape(5, 5)
print("Original: ", arr)
print("Squared: ", np.square(arr))

Original:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Squared:  [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [24]:
five_six = np.arange(30).reshape(5, 6)
print("Original: ", five_six)
print("Mean: ", np.mean(five_six))

Original:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [26]:
np.std(five_six)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [27]:
np.median(five_six)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [28]:
np.transpose(five_six)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [30]:
diagonal_array = np.arange(16).reshape(4, 4)
np.trace(diagonal_array)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [31]:
np.linalg.det(diagonal_array)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [32]:
arr = np.arange(100).reshape(10, 10)

print("5th percentile of arr : ", 
       np.percentile(arr, 5))
print("95th percentile of arr : ",
       np.percentile(arr, 95))

5th percentile of arr :  4.95
95th percentile of arr :  94.05


## Question:15

### How to find if a given array has any null values?

In [34]:
arr = np.array([1,2,3,None,5])

is_null = lambda arr10: print("Array has null values") if None in arr else print("Array does not have any null values")

is_null(arr)

Array has null values
