# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vec = np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
vec2 = np.arange(10, 49)
vec2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
vec2.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
vec2.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__, np.show_config())

blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/conda/envs/notebook/include']
1.19.2 None


7. Print the dimension of the array in question 3


In [7]:
vec2.ndim

1

8. Create a boolean array with all the True values

In [8]:
vec3 = np.array(range(1, 10), dtype="bool")
vec3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
vec4 = np.zeros((2, 2))
vec4

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [10]:
vec4 = np.zeros((3, 3, 3))
vec4

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
reverse_vector = np.array(range(1, 10))
print("Original: ", reverse_vector)

reverse_vector[0], reverse_vector[len(reverse_vector) - 1] = reverse_vector[len(reverse_vector) - 1], reverse_vector[0]

print("Modified: ", reverse_vector)

Original:  [1 2 3 4 5 6 7 8 9]
Modified:  [9 2 3 4 5 6 7 8 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null_vec  = np.zeros(10)
null_vec[5] = 1

null_vec

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
matrix = np.identity(3)

matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr  = np.array([1, 2, 3, 4, 5])
arr = arr.astype(np.float32)
arr

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.] ,[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.] ,[7., 2., 12.]])

np.multiply(arr1, arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


print("a > b") 
print(np.greater(arr1, arr2))

a > b
[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(9)
filtered_array = filter(lambda val: val % 2 == 0, arr)
list(filtered_array)

[0, 2, 4, 6, 8]

18. Replace all odd numbers to -1 from previous array

In [18]:
arr[arr % 2 == 0] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5] = arr[6] = arr[7] = arr[8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr = np.ones((8, 8))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

arr2d[1, 1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])

arr3d[0][:] = 64
arr3d[1][:] = 64

arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[64, 64, 64],
        [64, 64, 64]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr = np.arange(9).reshape(3, 3)
arr2 = arr[0] #TODO
arr2

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr = np.arange(9).reshape(3, 3)
val = arr[1][1] #TODO
val

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr = np.arange(9).reshape(3, 3)
arr3 = arr[0:-1, -1]

arr3

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.arange(100).reshape(10, 10)
maxInColumns = np.amax(arr, axis=1)
val = max(maxInColumns)
val

99

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [33]:

import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where(name[data] != "Will"))

[6 0 3 0 6 3 2]
(array([0, 1, 2, 3, 4, 5]),)


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [34]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where((name[data] != "Joe") & (name[data] != "Will")))

[1 4 1 4 0]
(array([4]),)


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [36]:

arr = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr

array([[ 8.01138063,  4.57566798, 10.12031286],
       [ 4.5092194 , 10.04494549,  4.69328988],
       [13.11127576,  6.82239613,  2.03508657],
       [13.56607274, 13.71078718,  5.676763  ],
       [ 9.66102072, 13.83440764,  1.84836221]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [37]:
arr_klo = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))

33. Swap axes of the array you created in Question 32

In [38]:
np.swapaxes(arr_klo, 0, 1)
arr_klo

array([[[ 5.99890079, 12.13583108,  9.04749978,  7.01581676],
        [11.24733336,  4.18965224,  3.95968956,  7.52417864]],

       [[ 4.41815492,  5.66811991, 12.6059893 , 11.79635439],
        [ 4.35045113, 15.24632723,  4.63232794,  2.23064745]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [39]:
import math

arr = np.arange(10)
print(arr)
new_arr = filter(lambda x: x if math.sqrt(x) > 0.5 else 0, arr)
np.asarray(list(new_arr))

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [40]:
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
np.where(arr1 == arr2)

[9]
[]


(array([], dtype=int64),)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [42]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)

a = filter(lambda x: x if x not in val else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [43]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray[:, 1] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [44]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [49]:
matrix = np.random.randint(20, size=(random.randint(0, 5), random.randint(0, 5)))
np.cumsum(matrix)

array([14, 23, 30, 45, 54, 61])